[book]
authors = ["Zicklag"]
multilingual = false
src = "book"
title = "Arsenal Game Engine"

[build]
build-dir = "build/book"

[output.html]
git_repository_url = "https://github.com/katharostech/arsenal"
