[workspace]
members = [
    # Arsenal crates
    "arsenal_blender_core",
    "arsenal_runtime",
    "arsenal_scripting",

    # Language adapters
    "arsenal_scripting/language_adapters/python",

    # Cargo utilities
    "xtask",
]
exclude = [
    "lib"
]